### ISSUE TITLE
No verification mail is send

### ISSUE THREAD

**Issue by mgk89** [fethica/PHP-Login#11]
On localhost it works perfectly, but online tests always result with:
![image](https://cloud.githubusercontent.com/assets/11804601/15583641/f5acc1a6-2376-11e6-8f20-e8319ce824a2.png)

The user gets created in the database, but no mail is send. Email settings are the same as when I tried on localhost.

Any ideas? Thanks!

**Comment by therecluse26** [comment]
Hi @mgk89, without more details, my guess would be an issue with your mail server credentials or perhaps some sort of firewall setting, but I can't be sure without additional information. Since circumstances vary so much from project to project and our mailer utilizes an external library, I would recommend opening an issue with your configuration details on the PHPMailer author's repository and see if they have any suggestions. Here's their repo: https://github.com/PHPMailer/PHPMailer

Sorry it's not working for you, please let us know if you find an issue in our code that is causing this problem!

**Comment by mgk89** [comment]
Hi, thanks for your answer! 
I figured it out, it was due to restrictions from my provider - but with the correct port setting it works ;) thanks for your help!

**Comment by therecluse26** [comment]
@mgk89 Glad you got it working! Just FYI I'm making some new updates right now which will include some a security feature and bug fixes, so keep an eye out for new commits in the near future :)
