### ISSUE TITLE
Logging for Fail2Ban

### ISSUE THREAD

**Issue by jb-alvarado** [fethica/PHP-Login#54]
I'm not a php expert, but I have search for a way to integrate PHP-Login in fail2ban. I add this to **checklogin.php**:

```
if ($response != 'true'){
	
	// write login failed in logfile for fail2ban
	$dat = date('M j H:i:s Y');
	$error_essage = "Authentication failed for: $username";
	$client_ip = $_SERVER['HTTP_CLIENT_IP']?:($_SERVER['HTTP_X_FORWARDE‌​D_FOR']?:$_SERVER['REMOTE_ADDR']);
	error_log("[$dat] [WARNING] [client: $client_ip] $error_essage\n", 3, "/var/log/php-login/login.log");
	
}
```
after line 55.

Is this a good way and place? What you think? I know you have a 5 min ban after some wrong logins, but I found this a bit saver.

My fail2ban filter looks like this:
```
[Definition]
failregex = \[WARNING\] \[client: <HOST>\] Authentication failed for: .*$
ignoreregex =
```
And my jail:

```
[php-login]
enabled  = true
port     = http,https
filter   = php-login
logpath  = /var/log/php-login/login.log
```

**Comment by therecluse26** [comment]
Hmm, interesting idea... I do wonder though how that would be integrated
into checking against banned users on the web application, since fail2ban
is a linux app. This would basically prevent users who fail from logging in
through PHP-Login from being able to connect to your actual server through
SSH, but it wouldn't prevent a jailed user from being able to log in
through PHP-Login in the future from what I can see.

This would also add another server-side dependency, which I would avoid if
possible.

**Comment by jb-alvarado** [comment]
Hello therecluse26, I agree with you, I also would avoid another dependency. If you would like - a feature where users a able to activate logging with a comment that is possible to use this logging for fail2ban would be totally enough.

In my example above I have only the ports for http and https where fail2ban blocks, if an user had multiple times a wrong login. SSH would still work. But you have also the option to block the IP for all services. 

As I see your prevention system goes on usernames. If I'm banned for some minutes, I can change to another user and I have a direct access again. Fail2ban banns IP addresses, which for me is better.
